### ISSUE TITLE
Files within deployment directory are not found in cloud

### ISSUE THREAD

**Issue by uzaymacar** [jina-ai/langchain-serve#100]
I have an `app.py` that reads a vectorstore file `vectorstore.pkl` in the same directory with:

```
path = "vectorstore.pkl"
with open(path, "rb") as f:
    ...
```

While this works fine locally, when deployed to Jina cloud with `lc-serve deploy jcloud app`, this throws a `File not found` error. By running the `os.listdir()` command, I am able to confirm that the `vectorstore.pkl` is not found in the cloud working directory.

A fix should be implemented such that all files within the deployment directory are included in the cloud working directory. A related issue can be found here: https://github.com/jina-ai/langchain-serve/issues/34.

### Interim solution

After chatting with @deepankarm, I solved this issue by using an absolute path with the `/appdir/` directory where the vectorstore file lives, i.e., using `path = "/appdir/vectorstore.pkl"`.

**Comment by deepankarm** [comment]
@uzaymacar Thanks for raising the issue. It should be fixed now. Please update to `>=0.0.42` and retry.
