### ISSUE TITLE
my streaming_handler is None

### ISSUE THREAD

**Issue by dinhan92** [jina-ai/langchain-serve#108]
Here is my code: I run debug and see that streaming_handler is None, I see in the example and the streaming_handler only appear in hitl file, I still don't know how to use it.

```python
@app.route('/api/chatbot', methods=['GET', 'POST'])
@token_required
@serving(websocket=True)
def chatbot(**kwargs) -> str:
    streaming_handler = kwargs.get('streaming_handler')
    input_text = request.data.decode("utf-8")
```

**Comment by dinhan92** [comment]
I am sorry, I just have check back. I see it has been changed, did you fix it ? @deepankarm ? ^^

**Comment by deepankarm** [comment]
Hey @dinhan92, can you please remove the app route and just use the `serving` decorator on its own? 

```python
@serving(websocket=True)
def chatbot(**kwargs) -> str:
    streaming_handler = kwargs.get('streaming_handler')
    input_text = request.data.decode("utf-8")
```
