### ISSUE TITLE
not found Interact, ServeHTTP

### ISSUE THREAD

**Issue by ngoanpv** [jina-ai/langchain-serve#122]
This is the code in the llm_chain example, I don't find package serve
`from serve import Interact, ServeHTTP`

**Comment by deepankarm** [comment]
Hey @ngoanpv, unfortunately, that was old code & we missed removing the readmes. I've removed them now. Please follow [this readme to deploy your apps as REST/WebSocket APIs](https://github.com/jina-ai/langchain-serve/blob/main/examples/rest/README.md) instead.
