### ISSUE TITLE
`@serving` functions in separate files

### ISSUE THREAD

**Issue by nicognaW** [jina-ai/langchain-serve#129]
Hi, I'm having an issue with inconsistent deployment behavior between deploying locally and on jCloud.

For my specific need, I have my app package, and all the `@serving` functions are declared in separate files in this app package like this:

```
├── app
│   ├── __init__.py
│   ├── app.py
│   ├── lcapp1.py
│   └── lcapp2.py
```

The `@serving` functions are declared in `lcapp1.py` and `lcapp2.py`, and if I import them in `__init__.py` like this:

```python
from .lcapp1 import *

from .lcapp2 import *

__all__ = ["lcapp1function", "lcapp2function"]
```

And with `lc-serve deploy local` I will have `lcapp1function` and `lcapp2function` APIs ready. But for `lc-serve deploy jcloud` these APIs will not be created.

I looked up the official implementations of apps, and they all have an `app.py` located in their app packages, I wonder if there's a recommended way to declare `@serving` function separately.

**Comment by nicognaW** [comment]
Alternatively, if I can deploy multiple apps in a single flow?

**Comment by deepankarm** [comment]
Hey @nicognaW, this is now supported with [v0.0.57](https://github.com/jina-ai/langchain-serve/releases/tag/v0.0.57) release. Please update to the latest version & [check out this example to deploy endpoints from different files](https://github.com/jina-ai/langchain-serve/tree/main/examples/directory#deploy-endpoints-from-different-files).
