### ISSUE TITLE
Add JSON parameters for babyagi websocket

### ISSUE THREAD

**Issue by Sassun** [jina-ai/langchain-serve#32]
I am trying to integrate the babyagi websocket socket that I have deployed on jcloud. It would be great to have an example and/or walkthrough integration of the WebSocket (e.g. required parameters to pass) to integrate on the client side.

**Comment by deepankarm** [comment]
Added here - https://github.com/jina-ai/langchain-serve#debug-babyagi-playground-requestresponse-for-external-integration
