### ISSUE TITLE
Expecting value: line 4 column 15 (char 79)

### ISSUE THREAD

**Issue by thomas-yanxin** [jina-ai/langchain-serve#42]
When I tried to use [langchain-serve](https://github.com/jina-ai/langchain-serve) in t[his project,](https://github.com/thomas-yanxin/LangChain-ChatGLM-Webui/blob/dev/jina_serving.py) I encountered such a problem. Could you please help me look at it?

![image](https://user-images.githubusercontent.com/58030051/234233851-a526fdbe-c19e-46e6-8d98-39ab49bd1d0a.png)

**Comment by deepankarm** [comment]
Hi @thomas-yanxin, thanks for trying lcserve. Could you please give us the steps to run the lc-serve command ourselves and please copy paste the curl command in a code format.

**Comment by deepankarm** [comment]
Can you please change `True` to `true` and retry?

```bash
curl -X 'POST' \
  'http://localhost:8080/predict' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "input": "ChatGLM-6B的具体局限性？",
  " file_path": "./README.md",
   "use_web": true,
   "top_k": 3,
   "history_len": 1,
   "temperature": 0.01,
   "top_p": 0.1,
   "history": []
}'
```

**Comment by thomas-yanxin** [comment]
Ok, I will try it now and have a conclusion to communicate with you here! Thanks!

**Comment by thomas-yanxin** [comment]
Success! Thanks!
