### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by WizKid1968** [jina-ai/langchain-serve#45]
Will someone help me install and run the qna_pdf application locally or through Jina. I would greatly appreciate it.

**Comment by deepankarm** [comment]
@WizKid1968 You can install langchain-serve using `pip install langchain-serve`, then deploy the qna app using `lc-serve deploy pdf-qna`. Please join our slack  to discuss further about any issues you might be facing.

**Comment by deepankarm** [comment]
Closing since no updates
