### ISSUE TITLE
cant lc serve

### ISSUE THREAD

**Issue by bllfoad** [jina-ai/langchain-serve#53]
'lc-serve' is not recognized as an internal or external command,
operable program or batch file.

**Comment by deepankarm** [comment]
Following up on [this issue](https://github.com/bhaskatripathi/pdfGPT/issues/42), I see that you were able to solve the issue with the command not found error. 

About the gateway being stuck error, can you please save this file as `file.py` and run `python file.py`?

```python
from jina import Flow, Executor, requests


class MyExecutor(Executor):
    @requests(on='/foo')
    def foo(self, parameters, **kwargs):
        print(f'In foo, got params {parameters}')

        
with Flow(protocol='http').add(uses=MyExecutor) as f:
    f.post(on='/foo', parameters={'a': 1, 'b': 2})
```

**Comment by riverind** [comment]
pip install langchain-serve
could solve it
