### ISSUE TITLE
DEPRECATION: langchain-serve is being installed using the legacy 'setup.py install'

### ISSUE THREAD

**Issue by bigKeter** [jina-ai/langchain-serve#60]
I'm getting the following warning when installing the package:

```
DEPRECATION: langchain-serve is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

**Comment by zac-li** [comment]
Thanks for reporting, we will work on enabling project with newer build system.

**Comment by deepankarm** [comment]
`pyproject.toml` file was added in this [commit](https://github.com/jina-ai/langchain-serve/pull/66/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711), which should fix this issue. Please reopen if not fixed yet.
