### ISSUE TITLE
Issue in self deploying langchain-serve

### ISSUE THREAD

**Issue by sundar7D0** [jina-ai/langchain-serve#68]
Can you provide more documentation on how to self-deploy langchain-serve on other cloud platforms like AWS?

**Comment by deepankarm** [comment]
Hi @sundar7D0, we are going to pick this up soon.

**Comment by deepankarm** [comment]
This is supported - https://github.com/jina-ai/langchain-serve#-self-host-llm-apps-with-docker-compose-or-kubernetes since [v0.0.43](https://github.com/jina-ai/langchain-serve/releases/tag/v0.0.43)
