### ISSUE TITLE
Is there any support for Data persistence？

### ISSUE THREAD

**Issue by pengxiao-song** [jina-ai/langchain-serve#87]
Hey! We are the team of [LaWGPT](https://github.com/pengxiao-song/LaWGPT), and your work is so wonderful!

Now, We have a demand that LaWGPT needs persistent storage of user question-and-answer data (data collection) for iterative project updates. So is there any support to cope with this problem?

Thank you very much!

**Comment by deepankarm** [comment]
@pengxiao-song glad to see you here.

> persistent storage of user question-and-answer data (data collection) for iterative project updates
Jina AI Cloud has support for persistent data storage. Few questions

- What kind of data format do you use?
- What data size do you expect?
- Any latency expectations from the data in/out operations?

**Comment by deepankarm** [comment]
Alright. Though Jina AI Cloud supports persistent storage, right now it is not exposed via langchain-serve. I'll work on this and let you know once released.

**Comment by pengxiao-song** [comment]
> Alright. Though Jina AI Cloud supports persistent storage, right now it is not exposed via langchain-serve. I'll work on this and let you know once released.

Thanks, very expected to your nice work!

**Comment by deepankarm** [comment]
@pengxiao-song persistent disk is now supported with the new release [0.0.36](https://github.com/jina-ai/langchain-serve/releases/tag/v0.0.36). You can [find the usage in the readme](https://github.com/jina-ai/langchain-serve#-persistent-storage-on-jina-ai-cloud).

**Comment by pengxiao-song** [comment]
> @pengxiao-song persistent disk is now supported with the new release [0.0.36](https://github.com/jina-ai/langchain-serve/releases/tag/v0.0.36). You can [find the usage in the readme](https://github.com/jina-ai/langchain-serve#-persistent-storage-on-jina-ai-cloud).

Nice work! I will take a look carefully later. Thanks!
