### ISSUE TITLE
lc-serve command not found

### ISSUE THREAD

**Issue by arthur-brainchain** [jina-ai/langchain-serve#95]
<img width="1196" alt="Screenshot 2023-05-28 at 4 43 45 PM" src="https://github.com/jina-ai/langchain-serve/assets/132293959/69e5088c-f190-47ac-8fb0-24a9b0dbce7e">

Sorry for the lack of detail, but after creating a jina.ai account and then performing the auth, and installing the project, I still can't seem to locate lc-serve - where is this file supposed to be or where does this script live?

**Comment by zac-li** [comment]
This requires installing `lc-serve` itself:

```
pip install langchain-serve
```

Have you done this?

**Comment by deepankarm** [comment]
And if some reason, `lc-serve` command is still not found after `langchain-serve` installation, you can try `python -m lcserve` instead.

**Comment by arthur-brainchain** [comment]
Yeah I had done the `pip install langchain-serve`, but I will try to do the `python -m lcserve` instead in a while. Thanks for posting, let me leave this open while I do some further testing. Should sync back up here in a few hours

**Comment by matipina** [comment]
I was having the same issue, but running it with `python -m lcserve` solved it for me, thanks!

**Comment by deepankarm** [comment]
@arthur-brainchain were you able to check this?

**Comment by deepankarm** [comment]
Closing as there are no updates.
