### ISSUE TITLE
Unable to import app.py: Instance and class checks can only be used with @runtime_checkable protocols

### ISSUE THREAD

**Issue by cyberandy** [jina-ai/langchain-serve#96]
Hi there, 

I am trying to deploy locally a langchain app using lc-serve but I am now getting this error. 
The code runs on Colab without issues; I am using llama-index. I am using version 0.0.38 (tried with both Python 3.9 and 3.10, same issue)

**Comment by cyberandy** [comment]
Same using 0.0.38

**Comment by JoanFM** [comment]
Hey @cyberandy ,

What is the error you are getting?

**Comment by cyberandy** [comment]
Hi there

<img width="971" alt="image" src="https://github.com/jina-ai/langchain-serve/assets/837037/36cb5e26-ace2-4de7-82e4-7bd348c7642b">

Here is the error I get just after launching the local deploy (`lc-serve deploy local app.py`)

`Unable to import app.py: Instance and class checks can only be used with @runtime_checkable protocols`
